[package]
name = "elis-app"
version = "0.0.1"
authors = ["jonlamb-gh <lamb.jon.io@gmail.com>"]

[dependencies.gtk]
version = "0.4.0"
features = ["v3_18"]

[dependencies]
elis-lib = { git = "https://github.com/jonlamb-gh/elis-lib.git", branch = "devel" }
gio = "^0"
glib = "^0"
